# Generated by Django 6.0.4 on 2026-04-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_article_slug_alter_article_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
