# Generated by Django 6.0.4 on 2026-04-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.AlterField(
            model_name='context',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/context/'),
        ),
    ]
