# Generated by Django 6.0.4 on 2026-05-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
